lint:
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
nf_core_version: 4.0.0
repository_type: pipeline
template:
  author: Aaryan Jaitly
  description: A bioinformatics pipeline for chromatin segmentation. It uses a hidden
    Markov model (HMM) to annotate genomic regions with functional states (e.g., enhancers,
    promoters) based on combinations of epigenetic modifications, capturing spatial
    relations via transition probabilities.
  force: false
  is_nfcore: true
  name: epigenomesegmentation
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - gpu
  version: 1.0.0dev
